#!/usr/bin/env python3
"""
Run subgraph extraction + LLM assessment without training.

Input graph should be generated by prepare_llm_hetero_graph.py.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict, deque
from datetime import datetime
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from agent.llm_client import get_llm_client  # noqa: E402


def _parse_ts(ts: str | None) -> datetime | None:
    if not ts:
        return None
    ts = ts.strip()
    if not ts:
        return None
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S"):
        try:
            return datetime.strptime(ts, fmt)
        except ValueError:
            continue
    try:
        return datetime.fromisoformat(ts)
    except Exception:
        return None


def load_graph(graph_path: Path) -> dict[str, Any]:
    return json.loads(graph_path.read_text(encoding="utf-8"))


def extract_subgraph(
    graph: dict[str, Any],
    product_tag: str | None,
    region: str | None,
    start_time: datetime | None,
    end_time: datetime | None,
    seed_node: str | None,
    k_hop: int,
) -> dict[str, Any]:
    nodes = graph.get("nodes", [])
    edges = graph.get("edges", [])

    node_by_id = {n["node_id"]: n for n in nodes}
    node_by_name = {n["name"]: n for n in nodes}

    # 1) edge-level time filtering
    edge_filtered = []
    for e in edges:
        ts = _parse_ts(e.get("timestamp"))
        if start_time and (ts is None or ts < start_time):
            continue
        if end_time and (ts is None or ts > end_time):
            continue
        edge_filtered.append(e)

    # 2) node-level filtering
    base_node_ids = set()
    for n in nodes:
        if product_tag and n.get("product_tag") != product_tag:
            continue
        if region and n.get("region") != region:
            continue
        base_node_ids.add(n["node_id"])

    # If no filter given, default to all nodes touched by filtered edges
    if not product_tag and not region:
        for e in edge_filtered:
            base_node_ids.add(e["source"])
            base_node_ids.add(e["target"])

    # 3) k-hop expansion around seed
    adjacency = defaultdict(set)
    for e in edge_filtered:
        s, t = e["source"], e["target"]
        adjacency[s].add(t)
        adjacency[t].add(s)

    if seed_node:
        if seed_node in node_by_name:
            seed_id = node_by_name[seed_node]["node_id"]
        else:
            seed_id = seed_node
        if seed_id not in node_by_id:
            raise ValueError(f"seed node not found: {seed_node}")

        allowed = set([seed_id])
        q = deque([(seed_id, 0)])
        visited = set([seed_id])
        while q:
            cur, depth = q.popleft()
            if depth >= k_hop:
                continue
            for nb in adjacency.get(cur, set()):
                if nb not in visited:
                    visited.add(nb)
                    allowed.add(nb)
                    q.append((nb, depth + 1))
        selected_nodes = allowed & base_node_ids if base_node_ids else allowed
    else:
        selected_nodes = set(base_node_ids)

    sub_edges = [e for e in edge_filtered if e["source"] in selected_nodes and e["target"] in selected_nodes]

    # keep connected nodes in selected edges; if edges empty, keep selected_nodes as-is
    if sub_edges:
        connected = set()
        for e in sub_edges:
            connected.add(e["source"])
            connected.add(e["target"])
        selected_nodes = connected

    sub_nodes = [node_by_id[nid] for nid in selected_nodes if nid in node_by_id]

    return {
        "meta": {
            "product_tag": product_tag,
            "region": region,
            "start_time": start_time.isoformat() if start_time else None,
            "end_time": end_time.isoformat() if end_time else None,
            "seed_node": seed_node,
            "k_hop": k_hop,
            "node_count": len(sub_nodes),
            "edge_count": len(sub_edges),
        },
        "nodes": sub_nodes,
        "edges": sub_edges,
    }


def summarize_subgraph(subgraph: dict[str, Any]) -> dict[str, Any]:
    nodes = subgraph["nodes"]
    edges = subgraph["edges"]

    if not nodes:
        return {
            "risk_level": "low",
            "risk_score": 0.0,
            "triggered_rules": [],
            "evidence": {"inspections": [], "events": []},
            "supply_chain_context": {"nodes": [], "edges": [], "complexity_score": 0.0},
            "similar_cases": [],
            "top_nodes": [],
        }

    risk_scores = [float(n.get("risk_score", 0.0)) for n in nodes]
    avg_risk = sum(risk_scores) / max(len(risk_scores), 1)

    high_cnt = sum(1 for n in nodes if n.get("risk_level") == "high")
    med_cnt = sum(1 for n in nodes if n.get("risk_level") == "medium")

    if avg_risk >= 0.45 or high_cnt >= max(1, len(nodes) // 8):
        risk_level = "high"
    elif avg_risk >= 0.25 or med_cnt >= max(1, len(nodes) // 4):
        risk_level = "medium"
    else:
        risk_level = "low"

    risk_score_100 = round(avg_risk * 100, 2)
    top_nodes = sorted(nodes, key=lambda x: float(x.get("risk_score", 0.0)), reverse=True)[:5]

    triggered_rules = [
        {
            "factor": "subgraph_high_risk_node_ratio",
            "reason": f"high={high_cnt}/{len(nodes)}",
            "score": round(min(100, 30 + high_cnt * 8), 2),
        },
        {
            "factor": "subgraph_avg_node_risk",
            "reason": f"avg_node_risk={avg_risk:.3f}",
            "score": round(min(100, avg_risk * 100), 2),
        },
        {
            "factor": "subgraph_structure_complexity",
            "reason": f"nodes={len(nodes)}, edges={len(edges)}",
            "score": round(min(100, len(edges) / max(len(nodes), 1) * 20), 2),
        },
    ]

    supply_chain_context = {
        "nodes": [{"id": n["node_id"], "name": n["name"], "risk": n.get("risk_level")} for n in top_nodes],
        "edges": edges[:20],
        "complexity_score": round(len(edges) / max(len(nodes), 1), 3),
    }

    return {
        "risk_level": risk_level,
        "risk_score": risk_score_100,
        "triggered_rules": triggered_rules,
        "evidence": {"inspections": [], "events": []},
        "supply_chain_context": supply_chain_context,
        "similar_cases": [],
        "top_nodes": top_nodes,
    }


def run_assessment(args: argparse.Namespace) -> dict[str, Any]:
    graph = load_graph(Path(args.graph).resolve())
    subgraph = extract_subgraph(
        graph=graph,
        product_tag=args.product_tag,
        region=args.region,
        start_time=_parse_ts(args.start_time),
        end_time=_parse_ts(args.end_time),
        seed_node=args.seed_node,
        k_hop=args.k_hop,
    )

    summary = summarize_subgraph(subgraph)

    use_mock = args.use_mock_llm or not bool(os.environ.get("MINIMAX_API_KEY"))
    llm = get_llm_client(use_mock=use_mock)

    target_name = f"Subgraph[{args.region or 'all'}|{args.product_tag or 'all'}]"
    response = llm.generate_risk_report(
        target_name=target_name,
        target_type="enterprise",
        risk_level=summary["risk_level"],
        risk_score=summary["risk_score"],
        triggered_rules=summary["triggered_rules"],
        evidence=summary["evidence"],
        supply_chain_context=summary["supply_chain_context"],
        similar_cases=summary["similar_cases"],
    )

    return {
        "query": {
            "product_tag": args.product_tag,
            "region": args.region,
            "start_time": args.start_time,
            "end_time": args.end_time,
            "seed_node": args.seed_node,
            "k_hop": args.k_hop,
        },
        "subgraph_meta": subgraph["meta"],
        "rule_summary": {
            "risk_level": summary["risk_level"],
            "risk_score": summary["risk_score"],
            "top_nodes": [
                {
                    "node_id": n["node_id"],
                    "name": n["name"],
                    "risk_level": n.get("risk_level"),
                    "risk_score": n.get("risk_score"),
                }
                for n in summary["top_nodes"]
            ],
        },
        "llm": {
            "success": response.success,
            "latency_ms": response.latency_ms,
            "error": response.error,
            "content": response.content,
            "usage": response.usage,
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Run no-training subgraph LLM assessment")
    parser.add_argument("--graph", required=True, help="Path to graph_llm_ready.json")
    parser.add_argument("--product-tag", default=None, help="Product tag filter (default: all)")
    parser.add_argument("--region", default="上海", help="Region filter (default: 上海)")
    parser.add_argument("--start-time", default=None, help="Start time, e.g. 2025-01-01 00:00:00")
    parser.add_argument("--end-time", default=None, help="End time, e.g. 2025-03-31 23:59:59")
    parser.add_argument("--seed-node", default=None, help="Seed node name or node_id for k-hop extraction")
    parser.add_argument("--k-hop", type=int, default=2, help="k-hop neighborhood depth")
    parser.add_argument("--use-mock-llm", action="store_true", help="Force mock llm")
    parser.add_argument("--output", default="", help="Output json file path")
    args = parser.parse_args()

    result = run_assessment(args)

    if args.output:
        out = Path(args.output).expanduser().resolve()
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"[OK] assessment saved: {out}")
    else:
        print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
